### ISSUE TITLE
inviteToRoom works but fails to parse JSON response and raises exception

### ISSUE THREAD

**Issue by schoettl** [softwarefactory-project/matrix-client-haskell#32]
I use this client to create a room and then invite another user.

It works so far, it does create the room and invite the user. But then, I get an exception:

```
user error (Error in $: parsing () failed, expected Array, but encountered Object)
```

It seems to be a Aeson parse exception on the response returned by the matrix server. I could only handle that exception with a try/catch but it seems like a bug in this package to me.

I'm using version 0.1.4.3 (latest on hackage).

-----

This is my code:

```haskell
createPrivateMatrixRoom :: ClientSession -> Text -> Text -> Text -> [UserID] -> IO ()
createPrivateMatrixRoom sess alias name description users = do
  roomResult <- createRoom sess $ RoomCreateRequest PrivateChat alias name description
  case roomResult of
    Right roomId -> do
      inviteResults <- mapM (flip (inviteToRoom sess roomId) Nothing) users
      case lefts inviteResults of
        [] -> return ()
        err -> error $ "error: could not invite some users. details: " ++ show err
    Left err -> error $ "error: could not create matrix room, maybe due to existing canonical alias. details: " ++ show err
```

**Comment by schoettl** [comment]
It looks like [`inviteToRoom`](https://github.com/softwarefactory-project/matrix-client-haskell/blob/master/matrix-client/src/Network/Matrix/Client.hs#L630) calls `doRequest` and implicitly specifies the return type to be `MatrixIO ()` and then `doRequest` tries to parse the JSON response to `()`.

I'll try if I can provide a fix.

**Comment by schoettl** [comment]
With `traceShowId`:

```
"{\"room_id\":\"!cFEKmHKNNDNsWDRGUv:matrix.org\"}"    -- room create work
"{}"  -- invite user also worked, empty JSON object as response
14/Mar/2023:11:42:15 +0100 [Error#yesod-core] user error (Error in $: parsing () failed, expected Array, but encountered Object)
```

**Comment by schoettl** [comment]
Oh, this kind of bug was already fixed for other functions of type `MatrixIO ()`.

It was fixed in many different ways:

- `fmap (() <$) $ doRequest' @Value manager req`
- `fmap ensureEmptyObject <$> doRequest session (request {HTTP.method = "POST"})`
- `void <$> (doRequest session $ request { ... })`

I was close to publishing another possible fix :D

**Comment by TristanCacqueray** [comment]
Thank you for the bug report and for improving the error handling. It seems like this depends on the server implementation, in #35 I'm adding an invite test that works against conduit.rs.

In the future, we might want to remove the exception throwing by using the existing MatrixError data to return such decoding error.
