### ISSUE TITLE
restrictive upper bounds on aeson and text

### ISSUE THREAD

**Issue by maralorn** [softwarefactory-project/matrix-client-haskell#36]
Just a heads up, currently the lib has these bounds:
```
Error: Setup: Encountered missing or private dependencies:
aeson >=1.0.0.0 && <2.1, text >=0.11.1.0 && <1.3
```

But it seems to build fine with aeson 2.1 and text 2.0

**Comment by TristanCacqueray** [comment]
Thanks for the feedback. I've published a new revision with the new bounds.
